-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.sweetdealtrip
(
    time_stamp timestamp without time zone NOT NULL,
    trip_id character varying COLLATE pg_catalog."default" NOT NULL,
    depart_airport character varying(4) COLLATE pg_catalog."default" NOT NULL,
    return_airport character varying(4) COLLATE pg_catalog."default" NOT NULL,
    depart_date date NOT NULL,
    return_date date NOT NULL,
    total_cost integer NOT NULL,
    depart_datetime timestamp without time zone NOT NULL,
    depart_duration integer NOT NULL,
    depart_stops integer NOT NULL,
    return_datetime timestamp without time zone NOT NULL,
    return_duration integer NOT NULL,
    return_stops integer NOT NULL,
    days_before_purchase integer NOT NULL,
    CONSTRAINT sweetdealtrip_pkey PRIMARY KEY (time_stamp)
)
WITH (
    OIDS = FALSE
);
END;